=== phreborn/vbfcp_xmlAnaWSBuilder/dtd/AnaWSBuilder.dtd
<!ELEMENT Combination (Input+,POI*,Correlate*,Asimov*)> <!-- Correlate here is dummy and only included for backward compatibility -->
<!ATTLIST Combination
          WorkspaceName      CDATA            #REQUIRED
          ModelConfigName    CDATA            #REQUIRED
          DataName           CDATA            #REQUIRED
          OutputFile         CDATA            #REQUIRED
	  Blind              CDATA            #IMPLIED
> 

<!ELEMENT Input (#PCDATA) >

<!ELEMENT POI (#PCDATA) >

<!ELEMENT Asimov EMPTY>
<!ATTLIST Asimov
          Name              CDATA            #REQUIRED
	  Setup             CDATA            #IMPLIED
	  Action            CDATA            #IMPLIED
	  SnapshotAll       CDATA            #IMPLIED
	  SnapshotGlob      CDATA            #IMPLIED
	  SnapshotNuis      CDATA            #IMPLIED
	  SnapshotPOI       CDATA            #IMPLIED
	  Injection         CDATA            #IMPLIED
	  >

<!ELEMENT Channel (Data,Correlate*,(Systematic | Item | ImportItems | IncludeSysts)*,Sample+)>
<!ATTLIST Channel
          Name              CDATA            #REQUIRED
	  Type              CDATA            #REQUIRED
	  Lumi              CDATA            #IMPLIED
	  >

<!ELEMENT Correlate (#PCDATA) >

<!ELEMENT Data EMPTY>
<!ATTLIST Data
          InputFile         CDATA            #IMPLIED
          FileType          CDATA            #IMPLIED
	  TreeName          CDATA            #IMPLIED
	  VarName           CDATA            #IMPLIED
	  Cut               CDATA            #IMPLIED
          Observable        CDATA            #REQUIRED
          Binning           CDATA            #IMPLIED
          InjectGhost       CDATA            #IMPLIED
	  NumData           CDATA            #IMPLIED
	  BlindRange        CDATA            #IMPLIED
	  >

<!ELEMENT Item  EMPTY>
<!ATTLIST Item 
	  Name                 CDATA         #REQUIRED
	  >

<!ELEMENT Sample ( Systematic | NormFactor | ShapeFactor | ImportItems )*>
<!ATTLIST Sample
          Name              CDATA            #REQUIRED
	  Norm              CDATA            #IMPLIED
	  XSection          CDATA            #IMPLIED
	  BR                CDATA            #IMPLIED
	  SelectionEff      CDATA            #IMPLIED
	  Acceptance        CDATA            #IMPLIED
	  Correction        CDATA            #IMPLIED
          InputFile         CDATA            #IMPLIED
          ImportSyst        CDATA            #IMPLIED
          MultiplyLumi      CDATA            #IMPLIED
	  SharePdf          CDATA            #IMPLIED
	  > 

<!ELEMENT Systematic EMPTY>
<!ATTLIST Systematic
          Name              CDATA            #REQUIRED
          Constr            CDATA            #REQUIRED
	  CentralValue      CDATA            #REQUIRED
          Mag               CDATA            #REQUIRED
	  WhereTo           CDATA            #REQUIRED
	  Process           CDATA            #IMPLIED
	  > 

<!ELEMENT NormFactor EMPTY>
<!ATTLIST NormFactor
          Name              CDATA            #REQUIRED
	  Correlate         CDATA            #IMPLIED
	  > 

<!ELEMENT ShapeFactor EMPTY>
<!ATTLIST ShapeFactor
          Name              CDATA            #REQUIRED
          Correlate         CDATA            #IMPLIED
	  >

<!ELEMENT Model (Item | Rename | ModelItem | Fix | ExtSyst)*>

<!ATTLIST Model
	  Type              CDATA            #REQUIRED
	  Input             CDATA            #IMPLIED
	  WSName            CDATA            #IMPLIED
	  ModelName         CDATA            #IMPLIED
	  ObservableName    CDATA            #IMPLIED
	  CacheBinning      CDATA            #IMPLIED
	  Rebin             CDATA            #IMPLIED
	  >

<!ELEMENT ModelItem  EMPTY>
<!ATTLIST ModelItem
	  Name                 CDATA         #REQUIRED
	  >

<!ELEMENT Rename  EMPTY>
<!ATTLIST Rename
	  OldName                 CDATA         #REQUIRED
	  NewName                 CDATA         #REQUIRED
	  >

<!ELEMENT Fix  EMPTY>
<!ATTLIST Fix
	  Name                 CDATA         #REQUIRED
	  Value                CDATA         #IMPLIED
	  >

<!ELEMENT ExtSyst  EMPTY>
<!ATTLIST ExtSyst
	  NPName                 CDATA         #REQUIRED
	  GOName                 CDATA         #IMPLIED
	  ConstrName             CDATA         #IMPLIED
	  >

<!ELEMENT ImportItems  EMPTY>
<!ATTLIST ImportItems
	  FileName             CDATA         #REQUIRED
	  >

<!ELEMENT IncludeSysts  EMPTY> <!-- Obsolete: please use ImportItems -->
<!ATTLIST IncludeSysts
	  FileName             CDATA         #REQUIRED
	  >

<!ELEMENT SampleItems ( Systematic | Item | NormFactor | ShapeFactor )*>

=== phreborn/vbfcp_xmlAnaWSBuilder/config/ttHyy/model/signal_ttH_c33.xml
<!DOCTYPE Model SYSTEM 'AnaWSBuilder.dtd'>
<Model Type="UserDef">
  <Item Name="muCBNom[125.218]"/>
  <Item Name="sigmaCBNom[1.45454]"/>
  <Item Name="alphaCBLo[1.64719]"/>
  <Item Name="alphaCBHi[1.67187]"/>
  <Item Name="nCBLo[4.94469]"/>
  <Item Name="nCBHi[5.32902]"/>
  <Item Name="prod::muCB(muCBNom,resp_SCALE,response::ATLAS_LHCmass)"/>
  <Item Name="prod::sigmaCB(sigmaCBNom,resp_RES)"/>
  <ModelItem Name="RooTwoSidedCBShape::signal(:observable:, muCB, sigmaCB, alphaCBLo, nCBLo, alphaCBHi, nCBHi)"/>
</Model>

=== phreborn/vbfcp_xmlAnaWSBuilder/config/ttH/model/signal_7TeV_ttHlep.xml
<!DOCTYPE Model SYSTEM 'AnaWSBuilder.dtd'>
<Model Type="UserDef">
  <Item Name="RooPolyVar::mHiggsCB(dmH, {sum::mCBterm0(mH,mCBpar0[0.030176]), mCBpar1[-0.003099], 0})"/>
  <Item Name="RooPolyVar::alphaCB(dmH, {aCBpar0[1.607700],aCBpar1[0.000000]}, 0)"/>
  <Item Name="RooPolyVar::sigmaCB(dmH, {sCBpar0[1.350000],sCBpar1[0.005788]}, 0)"/>
  <Item Name="RooPolyVar::frac(dmH, {fCBpar0[0.983700],fCBpar1[0.000000]}, 0)"/>
  <Item Name="RooPolyVar::kGA(dmH, {kGApar0[4.701900],kGApar1[0.000000]}, 0)"/>
  <Item Name="RooPolyVar::mHiggsGA(dmH, {sum::mGAterm0(mH,mGApar0[-0.294983]),mGApar1[0.016798]}, 0)"/>
  <Item Name="RooGaussian::tailPdf(:observable:, prod::mHiggsTail(mHiggsGA,resp_MSS), prod::sigmaTail(resp_mRES,sigmaCB,kGA))"/>
  <Item Name="RooCBShape::peakPdf(:observable:, prod::mHiggsCore(mHiggsCB,resp_MSS), prod::sigmaCore(resp_mRES,sigmaCB), alphaCB, 10)"/>
  <ModelItem Name="SUM::signalPdf(frac*peakPdf,tailPdf)"/>
</Model>

=== phreborn/vbfcp_xmlAnaWSBuilder/config/ttH/ttH_run1.xml
<!DOCTYPE Combination  SYSTEM 'AnaWSBuilder.dtd'>  
<Combination WorkspaceName="combWS" ModelConfigName="ModelConfig" DataName="combData" OutputFile="workspace/ttH/tth.root" >
  <Input>config/ttH/ttHhad.xml</Input>
  <Input>config/ttH/ttHlep.xml</Input>
  <Input>config/ttH/7TeV_ttHhad.xml</Input>
  <Input>config/ttH/7TeV_ttHlep.xml</Input>
  <POI>mu_ttH,mu,mH</POI>
  <Asimov Name="AsimovB"  Setup="mu=0,mH=125.4"      Action="fixsyst:fit:genasimov:float:savesnapshot" SnapshotAll="ucmles_0" SnapshotNuis="nominalNuis" SnapshotGlob="nominalGlob"/>
  <Asimov Name="AsimovSB"  Setup="mu=1,mH=125.4"     Action="genasimov:reset"/>
  <Asimov Name="single_mu_fit" Setup="mu=1_0_5,mu_ttH=1,mH=125.4" Action="fit:savesnapshot:reset" SnapshotAll="ucmles_mu" SnapshotNuis="conditionalNuis_muhat" SnapshotGlob="conditionalGlob_muhat"/>
  <Asimov Name="single_mu_ttH_fit" Setup="mu_ttH=1_0_5,mu=1,mH=125.4" Action="fit:savesnapshot" SnapshotAll="ucmles_mu_ttH" SnapshotNuis="conditionalNuis_mu_ttHhat" SnapshotGlob="conditionalGlob_mu_ttHhat"/>
</Combination>

=== phreborn/vbfcp_xmlAnaWSBuilder/config/high_mass_diphoton/graviton/2015/signal_2015_Graviton_13TeV_2D_EKHI_v36.xml
<!DOCTYPE Model SYSTEM 'AnaWSBuilder.dtd'>
<Model Type="UserDef" CacheBinning="100000">
  <Item Name="expr::muCB('@1+@2*@0+@3*@0*@0',mnX, a_muCB[-0.293752],b_muCB[-0.0273403],c_muCB[-0.00156661])"/>
  <Item Name="expr::sigmaCBNom('@1+@2*@0',mnX, a_sigmaCBNom[2.16397],b_sigmaCBNom[0.749941])"/>
  <Item Name="prod::sigmaCB(sigmaCBNom, response::ATLAS_mRes:process:)"/>
  <Item Name="expr::alphaCBLo('@1+@2*@0+@3*@0*@0', mnX,a_alphaCBLo[1.94589],b_alphaCBLo[-0.00209894], c_alphaCBLo[-3.16281e-05])"/>
  <Item Name="expr::alphaCBHi('@1+@2*@0+@3*@0*@0', mnX,a_alphaCBHi[2.27144],b_alphaCBHi[-0.0138342], c_alphaCBHi[0.000299028])"/>
  <Item Name="nCBLo[3.22211]"/>
  <Item Name="nCBHi[3.61315]"/>
  <Item Name="alpha[1.5]"/>
  <Item Name="expr::wG('1.44*@0*@0*@1',GkM,mG)"/>
  <Item Name="HggTwoSidedCBPdf::detector(:observable:, muCB, sigmaCB, alphaCBLo, nCBLo, alphaCBHi, nCBHi)"/>
  <Item Name="HggMG5aMCNLOLineShapePdf::truth(:observable:, mG, wG, alpha, 13)"/>
  <ModelItem Name="RooFFTConvPdf::signal(:observable:, truth, detector)"/>
</Model>

=== phreborn/vbfcp_xmlAnaWSBuilder/config/high_mass_diphoton/graviton/2016/category_2016_Graviton_13TeV_histfactory_EKHI_v36.xml
<!DOCTYPE Channel SYSTEM 'AnaWSBuilder.dtd'>
<Channel Name="inclusive_13TeV_2016_EKHI" Type="shape" Lumi="33.5196">
  <Data InputFile="Input/data/high_mass_diphoton/data16/mass_points_data16_13TeV_EKHI_33.5ifb_h015.txt" Observable="obs_x_channel[200,5000]" Binning="960" InjectGhost="1"/>
  
  <Item Name="mG[750, 700, 800]"/>
  <Item Name="GkM[0.1, 0, 1]"/>
  <Item Name="expr::mnX('(@0 - 100.)/100.', mG)"/>

  <Item Name="expr::uncert_ph_eff('(@1 + @2*exp(@3*@0))/100.', mG, sigmaEffSignal0[3.08], sigmaEffSignal1[-45.1], sigmaEffSignal2[-0.00901])"/>

  <Item Name="expr::uncert_ph_cal_iso('(@1 + @2*exp(@3*@0))/100.', mG, sigmaCalIsol0[0.0448], sigmaCalIsol1[-1.15], sigmaCalIsol2[-0.00135])"/>
  <Item Name="expr::uncert_ph_trk_iso('(@1 + @2*@0)/100.', mG, sigmaTrkIsol0[1.349], sigmaTrkIsol1[-0.00002571])"/>
  <Item Name="expr::uncert_ph_iso('sqrt(@0*@0+@1*@1)', uncert_ph_cal_iso, uncert_ph_trk_iso)"/>
  
  <Item Name="expr::cbSigmaSignal0('@1 + @2*@0', mnX, sCBSignal0[2.16397], sCBSignal1[0.749941])"/>
  <Item Name="expr::cbSigmaSignalUp('@1 + @2*@0', mnX, sCBSignal0Up[2.61879], sCBSignal1Up[1.02842])"/>
  <Item Name="expr::cbSigmaSignalDn('@1 + @2*@0', mnX, sCBSignal0Dn[2.01965], sCBSignal1Dn[0.466404])"/>
  
  <Item Name="expr::uncert_mres_hi('(@1 - @0)/@0', cbSigmaSignal0, cbSigmaSignalUp)"/>
  <Item Name="expr::uncert_mres_lo('(@0 - @1)/@0', cbSigmaSignal0, cbSigmaSignalDn)"/>

  <Sample Name="signal" XSection="1" SelectionEff="1" InputFile="config/high_mass_diphoton/graviton/2016/signal_2016_Graviton_13TeV_2D_EKHI_v36.xml" MultiplyLumi="1">
    <Systematic Name="ATLAS_lumi"      Constr="logn" CentralValue="1" Mag="0.0114" WhereTo="yield"/>
    <Systematic Name="ATLAS_lumi_2016" Constr="logn" CentralValue="1" Mag="0.0323" WhereTo="yield"/>
    <Systematic Name="ATLAS_PH_EFF"    Constr="logn" CentralValue="1" Mag="uncert_ph_eff" WhereTo="yield"/>
    <Systematic Name="ATLAS_PH_ISO"    Constr="logn" CentralValue="1" Mag="uncert_ph_iso" WhereTo="yield"/>
    <Systematic Name="ATLAS_mRes"      Constr="asym" CentralValue="1" Mag="uncert_mres_hi,uncert_mres_lo" WhereTo="shape"/>
    <!-- <Systematic Name="ATLAS_ESS"       Constr="logn" CentralValue="1" Mag="uncert_ess" WhereTo="shape"/> -->
    <NormFactor Name="expr::AX('(@1 + @2*exp(@3*@0) + @4*exp(@5*@0))', mG, AX0[0.657], AX1[-0.346], AX2[-0.00419], AX3[-0.223], AX4[-0.000630])"/>
    <Systematic Name="ATLAS_AX" Constr="logn" CentralValue="1" Mag="0.029" WhereTo="yield"/>
    <NormFactor Name="xs[0,0,1000]" />
    <NormFactor Name="xs_2016[1]" />
  </Sample>
  
  <Sample Name="background" XSection="1" SelectionEff="1" InputFile="config/high_mass_diphoton/graviton/2016/background_2016_Graviton_13TeV_histfactory_EKHI_v36.xml" MultiplyLumi="0">
    <NormFactor Name="nbkg_inclusive_13TeV_2016_EKHI[7000,0,100000]" />
  </Sample>
</Channel>

=== phreborn/vbfcp_xmlAnaWSBuilder/config/bbyy/side.xml
<!DOCTYPE Channel SYSTEM 'AnaWSBuilder.dtd'>
<Channel Name="side" Type="counting" Lumi="20.3">
  <Data NumData="9" Observable="atlas_invMass_side[0,1]"/>
  
  <Systematic Name="ATLAS_lumi_2012" Constr="logn" CentralValue="1" Mag="0.028" WhereTo="yield"/>
  <Systematic Name="ATLAS_PHOTON_ID" Constr="logn" CentralValue="1" Mag="0.0245" WhereTo="yield"/>
  <Systematic Name="ATLAS_PHOTON_ISO" Constr="logn" CentralValue="1" Mag="0.02" WhereTo="yield"/>
  
  <Systematic Name="SigFracYY" Constr="logn" CentralValue="1" Mag="0.016" WhereTo="shape"/>
  <Systematic Name="SigMassYY" Constr="logn" CentralValue="1" Mag="0.017" WhereTo="shape"/>

  <Item Name="srFracYY[0.926145]"/>
  <Item Name="srFracYYBB[0.95]"/>
  <Item Name="effiYYBB[0.180071]"/>
  <Item Name="smEffiYYBB[0.107006]"/>
  <Item Name="extrapYY[0.147]"/>
  <Item Name="BRyy[0.00228]"/>
  <Item Name="BRbb[0.569]"/>
  <Item Name="cutsEffi[0.0430209]"/>
  <Item Name="luminosity[20276.9]"/>

  <!-- "response::" pre-fix means response term from a systematic uncertainty -->
  <Item Name="prod::kSigFracYY(response::SigFracYY, response::SigMassYY)"/>
  
  <Item Name="expr::ScaleFactorSM('1-@0*@1', srFracYY, kSigFracYY)"/>
  <Item Name="expr::ScaleFactorBSM('(1-@0*@1)*(2*@2*@3*@4*@5)', srFracYY, kSigFracYY, BRyy, BRbb,cutsEffi,luminosity)"/>
  <Item Name="ScaleFactorBkg[1]"/>

  <Sample Name="ggH" Norm="0.025407" ImportSyst=":common:" MultiplyLumi="0" SharePdf="commonCounting">
    <Systematic Name="BR_gamgam" Constr="logn" CentralValue="1" Mag="0.049" WhereTo="yield"/>
    <Systematic Name="QCDscale_ggH" Constr="asym" CentralValue="1" Mag="+0.072,-0.078" WhereTo="yield"/>
    <Systematic Name="pdf_gg" Constr="asym" CentralValue="1" Mag="+0.075,-0.069" WhereTo="yield"/>    
    <Systematic Name="HF_gg" Constr="logn" CentralValue="1" Mag="2.0" WhereTo="yield"/>    
    <Systematic Name="ATLAS_stat_ggH" Constr="logn" CentralValue="1" Mag="0.13" WhereTo="yield"/>    
    <Systematic Name="ATLAS_JES" Constr="gaus" CentralValue="1" Mag="0.21" WhereTo="yield"/>
    <Systematic Name="ATLAS_JER" Constr="gaus" CentralValue="1" Mag="0.21" WhereTo="yield"/> 
    <Systematic Name="ATLAS_JVF" Constr="gaus" CentralValue="1" Mag="0.001" WhereTo="yield"/>
    <Systematic Name="ATLAS_BJES" Constr="gaus" CentralValue="1" Mag="0.07" WhereTo="yield"/> 
    <NormFactor Name="mu_XS8_ggH[1]" />
    <NormFactor Name="ScaleFactorSM" />
  </Sample>

  <Sample Name="VBF" Norm="0.004608" ImportSyst=":common:" MultiplyLumi="0" SharePdf="commonCounting">
    <Systematic Name="BR_gamgam" Constr="logn" CentralValue="1" Mag="0.049" WhereTo="yield"/>
    <Systematic Name="QCDscale_VBF" Constr="asym" CentralValue="1" Mag="+0.002,-0.002" WhereTo="yield"/>
    <Systematic Name="pdf_qq" Constr="asym" CentralValue="1" Mag="+0.027,-0.027" WhereTo="yield"/>    
    <Systematic Name="HF_qq" Constr="logn" CentralValue="1" Mag="1.5" WhereTo="yield"/>
    <Systematic Name="ATLAS_stat_VBF" Constr="logn" CentralValue="1" Mag="0.11" WhereTo="yield"/>
    <Systematic Name="ATLAS_JES" Constr="gaus" CentralValue="1" Mag="0.21" WhereTo="yield"/>
    <Systematic Name="ATLAS_JER" Constr="gaus" CentralValue="1" Mag="0.21" WhereTo="yield"/>
    <Systematic Name="ATLAS_JVF" Constr="gaus" CentralValue="1" Mag="0.001" WhereTo="yield"/>
    <Systematic Name="ATLAS_BJES" Constr="gaus" CentralValue="1" Mag="0.07" WhereTo="yield"/> 
    <NormFactor Name="mu_XS8_VBF[1]" />
    <NormFactor Name="ScaleFactorSM" />
  </Sample>

  <Sample Name="WH" Norm="0.001303" ImportSyst=":common:" MultiplyLumi="0" SharePdf="commonCounting">
    <Systematic Name="BR_gamgam" Constr="logn" CentralValue="1" Mag="0.049" WhereTo="yield"/>
    <Systematic Name="QCDscale_WH" Constr="asym" CentralValue="1" Mag="+0.01,-0.01" WhereTo="yield"/>
    <Systematic Name="pdf_qq" Constr="asym" CentralValue="1" Mag="+0.023,-0.023" WhereTo="yield"/>
    <Systematic Name="HF_qq" Constr="logn" CentralValue="1" Mag="1.5" WhereTo="yield"/>
    <Systematic Name="ATLAS_stat_WH" Constr="logn" CentralValue="1" Mag="0.17" WhereTo="yield"/>
    <Systematic Name="ATLAS_JES" Constr="gaus" CentralValue="1" Mag="0.21" WhereTo="yield"/>
    <Systematic Name="ATLAS_JER" Constr="gaus" CentralValue="1" Mag="0.21" WhereTo="yield"/>
    <Systematic Name="ATLAS_JVF" Constr="gaus" CentralValue="1" Mag="0.001" WhereTo="yield"/>
    <Systematic Name="ATLAS_BJES" Constr="gaus" CentralValue="1" Mag="0.07" WhereTo="yield"/> 
    <NormFactor Name="mu_XS8_WH[1]" />
    <NormFactor Name="ScaleFactorSM" />
  </Sample>

  <Sample Name="ZH" Norm="0.027678" ImportSyst=":common:" MultiplyLumi="0" SharePdf="commonCounting">
    <Systematic Name="BR_gamgam" Constr="logn" CentralValue="1" Mag="0.049" WhereTo="yield"/>
    <Systematic Name="QCDscale_ZH" Constr="asym" CentralValue="1" Mag="+0.031,-0.031" WhereTo="yield"/>
    <Systematic Name="pdf_qq" Constr="asym" CentralValue="1" Mag="+0.025,-0.025" WhereTo="yield"/>
    <Systematic Name="ATLAS_stat_ZH" Constr="logn" CentralValue="1" Mag="0.025" WhereTo="yield"/>
    <Systematic Name="ATLAS_JES" Constr="gaus" CentralValue="1" Mag="0.21" WhereTo="yield"/>
    <Systematic Name="ATLAS_JER" Constr="gaus" CentralValue="1" Mag="0.21" WhereTo="yield"/>
    <Systematic Name="ATLAS_JVF" Constr="gaus" CentralValue="1" Mag="0.001" WhereTo="yield"/>
    <Systematic Name="ATLAS_BJES" Constr="gaus" CentralValue="1" Mag="0.07" WhereTo="yield"/> 
    <NormFactor Name="mu_XS8_ZH[1]"/>
    <NormFactor Name="ScaleFactorSM" />
  </Sample>

  <Sample Name="ttH" Norm="0.138543" ImportSyst=":common:" MultiplyLumi="0" SharePdf="commonCounting">
    <Systematic Name="BR_gamgam" Constr="logn" CentralValue="1" Mag="0.049" WhereTo="yield"/>
    <Systematic Name="QCDscale_ttH" Constr="asym" CentralValue="1" Mag="+0.038,-0.093" WhereTo="yield"/>
    <Systematic Name="pdf_gg" Constr="asym" CentralValue="1" Mag="+0.081,-0.081" WhereTo="yield"/>
    <Systematic Name="ATLAS_stat_ttH" Constr="logn" CentralValue="1" Mag="0.010" WhereTo="yield"/>
    <Systematic Name="ATLAS_JES" Constr="gaus" CentralValue="1" Mag="0.21" WhereTo="yield"/>
    <Systematic Name="ATLAS_JER" Constr="gaus" CentralValue="1" Mag="0.21" WhereTo="yield"/>
    <Systematic Name="ATLAS_JVF" Constr="gaus" CentralValue="1" Mag="0.001" WhereTo="yield"/>
    <Systematic Name="ATLAS_BJES" Constr="gaus" CentralValue="1" Mag="0.07" WhereTo="yield"/> 
    <NormFactor Name="mu_XS8_ttH[1]"/>
    <NormFactor Name="ScaleFactorSM" />
  </Sample>

  <Sample Name="SMDH" Norm="0.036617" ImportSyst=":common:" MultiplyLumi="0" SharePdf="commonCounting">
    <Systematic Name="BR_gamgam" Constr="logn" CentralValue="1" Mag="0.049" WhereTo="yield"/>
    <Systematic Name="BR_bb" Constr="logn" CentralValue="1" Mag="0.033" WhereTo="yield"/>
    <Systematic Name="QCDscale_SMDH" Constr="asym" CentralValue="1" Mag="+0.203,-0.167" WhereTo="yield"/>
    <Systematic Name="pdf_gg" Constr="asym" CentralValue="1" Mag="+0.085,-0.069" WhereTo="yield"/>
    <Systematic Name="ATLAS_stat_SMDH" Constr="logn" CentralValue="1" Mag="0.012" WhereTo="yield"/>
    <Systematic Name="ATLAS_JES" Constr="gaus" CentralValue="1" Mag="0.21" WhereTo="yield"/>
    <Systematic Name="ATLAS_JER" Constr="gaus" CentralValue="1" Mag="0.21" WhereTo="yield"/>
    <Systematic Name="ATLAS_JVF" Constr="gaus" CentralValue="1" Mag="0.001" WhereTo="yield"/>
    <Systematic Name="ATLAS_BJES" Constr="gaus" CentralValue="1" Mag="0.07" WhereTo="yield"/> 
    <NormFactor Name="mu_XS8_SMDH[1]"/>
    <NormFactor Name="ScaleFactorSM" />
  </Sample>

  <Sample Name="BSM" Norm="1" ImportSyst=":common:" MultiplyLumi="0" SharePdf="commonCounting">
    <Systematic Name="BR_gamgam" Constr="logn" CentralValue="1" Mag="0.049" WhereTo="yield"/>
    <Systematic Name="BR_bb" Constr="logn" CentralValue="1" Mag="0.033" WhereTo="yield"/>
    <Systematic Name="ATLAS_stat_BSM" Constr="logn" CentralValue="1" Mag="0.017" WhereTo="yield"/>
    <Systematic Name="ATLAS_JES" Constr="gaus" CentralValue="1" Mag="0.038" WhereTo="yield"/>    
    <Systematic Name="ATLAS_JER" Constr="gaus" CentralValue="1" Mag="0.093" WhereTo="yield"/>
    <Systematic Name="ATLAS_JVF" Constr="gaus" CentralValue="1" Mag="0.002" WhereTo="yield"/> 
    <Systematic Name="ATLAS_BJES" Constr="gaus" CentralValue="1" Mag="0.022" WhereTo="yield"/> 
    <NormFactor Name="mu[1,0,50]"/>
    <NormFactor Name="ScaleFactorBSM" />
  </Sample>

  <Sample Name="Continuum" Norm="1" ImportSyst=":self:" MultiplyLumi="0" SharePdf="commonCounting">
    <NormFactor Name="nConinuum[9,0,20]" />
  </Sample>
</Channel>

=== phreborn/vbfcp_xmlAnaWSBuilder/config/ttHyy/ttHyy.xml
<!DOCTYPE Combination  SYSTEM 'AnaWSBuilder.dtd'>  
<Combination WorkspaceName="combWS" ModelConfigName="ModelConfig" DataName="combData" OutputFile="workspace/ttHyy/tthyy.root" >

  <Input>config/ttHyy/ttH_c27.xml</Input>
  <Input>config/ttHyy/ttH_c28.xml</Input>
  <Input>config/ttHyy/ttH_c29.xml</Input>
  <Input>config/ttHyy/ttH_c30.xml</Input>
  <Input>config/ttHyy/ttH_c31.xml</Input>
  <Input>config/ttHyy/ttH_c32.xml</Input>
  <Input>config/ttHyy/ttH_c33.xml</Input>
  <POI>mu_ttH,mu</POI>

  <Asimov Name="AsimovB"  Setup="mu=0"      Action="fixsyst:fit:genasimov:float:savesnapshot" SnapshotAll="ucmles_0" SnapshotNuis="nominalNuis" SnapshotGlob="nominalGlob"/>
  <Asimov Name="AsimovSB"  Setup="mu=1"     Action="genasimov:reset"/>
  <Asimov Name="single_mu_fit" Setup="mu=1_0_5,mu_ttH=1" Action="fit:savesnapshot:reset" SnapshotAll="ucmles_mu" SnapshotNuis="conditionalNuis_muhat" SnapshotGlob="conditionalGlob_muhat"/>
  <Asimov Name="single_mu_ttH_fit" Setup="mu_ttH=1_0_5,mu=1" Action="fit:savesnapshot" SnapshotAll="ucmles_mu_ttH" SnapshotNuis="conditionalNuis_mu_ttHhat" SnapshotGlob="conditionalGlob_mu_ttHhat"/>
  <Asimov Name="AsimovSB_postfit" Setup="mu_ttH=1,mu=1" Action="fit:matchglob:genasimov:savesnapshot:reset" SnapshotAll="ucmles_postfit_1" SnapshotNuis="conditionalNuis_1" SnapshotGlob="conditionalGlob_1"/>

</Combination>

=== phreborn/vbfcp_xmlAnaWSBuilder/config/high_mass_diphoton/graviton/high_mass_diphoton_Graviton_13TeV_histfactory_EKHI_v36.xml
<!DOCTYPE Combination  SYSTEM 'AnaWSBuilder.dtd'>
<Combination WorkspaceName="combWS" ModelConfigName="ModelConfig" DataName="combData" OutputFile="workspace/high_mass_diphoton/1516_Graviton_histfactory_EKHI_v36.root" >
  <Input>config/high_mass_diphoton/graviton/2015/category_2015_Graviton_13TeV_histfactory_EKHI_v36.xml</Input>
  <Input>config/high_mass_diphoton/graviton/2016/category_2016_Graviton_13TeV_histfactory_EKHI_v36.xml</Input>
  <POI>xs,mG,GkM,xs_2015,xs_2016</POI>
  <Asimov Name="POISnap"  Setup=""  Action="savesnapshot" SnapshotPOI="nominalPOI"/>
  <Asimov Name="NPSnap"   Setup="xs=0,mG=750,GkM=0.2"      Action="fixsyst:fit:float:savesnapshot:nominalPOI" SnapshotNuis="nominalNuis" SnapshotGlob="nominalGlobs"/>
  <Asimov Name="asimovData_0" Setup="xs=0,mG=750,GkM=0.2"      Action="fit:genasimov:matchglob:savesnapshot:nominalGlobs" SnapshotGlob="conditionalGlobs_0" SnapshotNuis="conditionalNuis_0"/>
  <Asimov Name="UCMLES0Snap" Setup=""      Action="savesnapshot" SnapshotAll="ucmles_0"/>
</Combination>
