=== phreborn/vbfcp_xmlAnaWSBuilder/dtd/AnaWSBuilder.dtd
<!ELEMENT Combination (Input+,POI*,Correlate*,Asimov*)> <!-- Correlate here is dummy and only included for backward compatibility -->
<!ATTLIST Combination
          WorkspaceName      CDATA            #REQUIRED
          ModelConfigName    CDATA            #REQUIRED
          DataName           CDATA            #REQUIRED
          OutputFile         CDATA            #REQUIRED
	  Blind              CDATA            #IMPLIED
> 

<!ELEMENT Input (#PCDATA) >

<!ELEMENT POI (#PCDATA) >

<!ELEMENT Asimov EMPTY>
<!ATTLIST Asimov
          Name              CDATA            #REQUIRED
	  Setup             CDATA            #IMPLIED
	  Action            CDATA            #IMPLIED
	  SnapshotAll       CDATA            #IMPLIED
	  SnapshotGlob      CDATA            #IMPLIED
	  SnapshotNuis      CDATA            #IMPLIED
	  SnapshotPOI       CDATA            #IMPLIED
	  Injection         CDATA            #IMPLIED
	  >

<!ELEMENT Channel (Data,Correlate*,(Systematic | Item | ImportItems | IncludeSysts)*,Sample+)>
<!ATTLIST Channel
          Name              CDATA            #REQUIRED
	  Type              CDATA            #REQUIRED
	  Lumi              CDATA            #IMPLIED
	  >

<!ELEMENT Correlate (#PCDATA) >

<!ELEMENT Data EMPTY>
<!ATTLIST Data
          InputFile         CDATA            #IMPLIED
          FileType          CDATA            #IMPLIED
	  TreeName          CDATA            #IMPLIED
	  VarName           CDATA            #IMPLIED
	  Cut               CDATA            #IMPLIED
          Observable        CDATA            #REQUIRED
          Binning           CDATA            #IMPLIED
          InjectGhost       CDATA            #IMPLIED
	  NumData           CDATA            #IMPLIED
	  BlindRange        CDATA            #IMPLIED
	  >

<!ELEMENT Item  EMPTY>
<!ATTLIST Item 
	  Name                 CDATA         #REQUIRED
	  >

<!ELEMENT Sample ( Systematic | NormFactor | ShapeFactor | ImportItems )*>
<!ATTLIST Sample
          Name              CDATA            #REQUIRED
	  Norm              CDATA            #IMPLIED
	  XSection          CDATA            #IMPLIED
	  BR                CDATA            #IMPLIED
	  SelectionEff      CDATA            #IMPLIED
	  Acceptance        CDATA            #IMPLIED
	  Correction        CDATA            #IMPLIED
          InputFile         CDATA            #IMPLIED
          ImportSyst        CDATA            #IMPLIED
          MultiplyLumi      CDATA            #IMPLIED
	  SharePdf          CDATA            #IMPLIED
	  > 

<!ELEMENT Systematic EMPTY>
<!ATTLIST Systematic
          Name              CDATA            #REQUIRED
          Constr            CDATA            #REQUIRED
	  CentralValue      CDATA            #REQUIRED
          Mag               CDATA            #REQUIRED
	  WhereTo           CDATA            #REQUIRED
	  Process           CDATA            #IMPLIED
	  > 

<!ELEMENT NormFactor EMPTY>
<!ATTLIST NormFactor
          Name              CDATA            #REQUIRED
	  Correlate         CDATA            #IMPLIED
	  > 

<!ELEMENT ShapeFactor EMPTY>
<!ATTLIST ShapeFactor
          Name              CDATA            #REQUIRED
          Correlate         CDATA            #IMPLIED
	  >

<!ELEMENT Model (Item | Rename | ModelItem | Fix | ExtSyst)*>

<!ATTLIST Model
	  Type              CDATA            #REQUIRED
	  Input             CDATA            #IMPLIED
	  WSName            CDATA            #IMPLIED
	  ModelName         CDATA            #IMPLIED
	  ObservableName    CDATA            #IMPLIED
	  CacheBinning      CDATA            #IMPLIED
	  Rebin             CDATA            #IMPLIED
	  >

<!ELEMENT ModelItem  EMPTY>
<!ATTLIST ModelItem
	  Name                 CDATA         #REQUIRED
	  >

<!ELEMENT Rename  EMPTY>
<!ATTLIST Rename
	  OldName                 CDATA         #REQUIRED
	  NewName                 CDATA         #REQUIRED
	  >

<!ELEMENT Fix  EMPTY>
<!ATTLIST Fix
	  Name                 CDATA         #REQUIRED
	  Value                CDATA         #IMPLIED
	  >

<!ELEMENT ExtSyst  EMPTY>
<!ATTLIST ExtSyst
	  NPName                 CDATA         #REQUIRED
	  GOName                 CDATA         #IMPLIED
	  ConstrName             CDATA         #IMPLIED
	  >

<!ELEMENT ImportItems  EMPTY>
<!ATTLIST ImportItems
	  FileName             CDATA         #REQUIRED
	  >

<!ELEMENT IncludeSysts  EMPTY> <!-- Obsolete: please use ImportItems -->
<!ATTLIST IncludeSysts
	  FileName             CDATA         #REQUIRED
	  >

<!ELEMENT SampleItems ( Systematic | Item | NormFactor | ShapeFactor )*>

=== phreborn/vbfcp_xmlAnaWSBuilder/config/bbyy/resonant_bbyy_run1.xml
<!DOCTYPE Combination  SYSTEM 'AnaWSBuilder.dtd'>  
<Combination WorkspaceName="combined" ModelConfigName="ModelConfig" DataName="res300_dataSet" OutputFile="workspace/bbyy/resonant_300.root" >
  <Input>config/bbyy/sr.xml</Input>
  <Input>config/bbyy/side.xml</Input>
  <POI>mu</POI>
  <Asimov Name="POISnap"  Setup=""  Action="savesnapshot" SnapshotPOI="nominalPOI"/>
  <Asimov Name="NPSnap"   Setup="mu=0"      Action="fixsyst:fit:float:savesnapshot:nominalPOI" SnapshotNuis="nominalNuis" SnapshotGlob="nominalGlobs"/>
  <Asimov Name="AsimovB"  Setup="mu=0"      Action="fit:genasimov:float:matchglob:savesnapshot:nominalGlobs" SnapshotAll="ucmles_0"/>
  <Asimov Name="fit_mu" Setup="mu=1_0_50" Action="fit:savesnapshot:reset" SnapshotAll="ucmles"/>
</Combination>

=== phreborn/vbfcp_xmlAnaWSBuilder/config/high_mass_diphoton/graviton/high_mass_diphoton_2015_Graviton_13TeV_histfactory_EKHI_v36.xml
<!DOCTYPE Combination  SYSTEM 'AnaWSBuilder.dtd'>
<!-- 2016.06.13 -->
<Combination WorkspaceName="combWS" ModelConfigName="ModelConfig" DataName="combData" OutputFile="workspace/high_mass_diphoton/2015_Graviton_histfactory_EKHI_v36.root" >
  <Input>config/high_mass_diphoton/graviton/2015/category_2015_Graviton_13TeV_histfactory_EKHI_v36.xml</Input>
  <POI>xs,mG,GkM</POI>
  <Asimov Name="POISnap"  Setup=""  Action="savesnapshot" SnapshotPOI="nominalPOI"/>
  <Asimov Name="asimovData_nominal"   Setup="xs=0,mG=750,GkM=0.2"      Action="fixsyst:fit:float:genasimov:savesnapshot:nominalPOI" SnapshotNuis="nominalNuis" SnapshotGlob="nominalGlobs"/>
  <Asimov Name="asimovData_0" Setup="xs=0,mG=750,GkM=0.2"      Action="fit:genasimov:matchglob:savesnapshot:nominalGlobs" SnapshotGlob="conditionalGlobs_0" SnapshotNuis="conditionalNuis_0"/>
  <Asimov Name="UCMLES0Snap" Setup=""      Action="savesnapshot" SnapshotAll="ucmles_0"/>
  <Asimov Name="asimovData_muhat" Setup="xs=20_0_100,mG=750_730_770,GkM=0.20_0.01_0.5"      Action="fit:genasimov:matchglob:savesnapshot:nominalGlobs" SnapshotGlob="conditionalGlobs_muhat" SnapshotNuis="conditionalNuis_muhat" SnapshotPOI="conditionalPOI_muhat"/>
  <Asimov Name="UCMLESSnap" Setup=""      Action="savesnapshot" SnapshotAll="ucmles"/>
</Combination>
